### ISSUE TITLE
Needs MO2 / SKSE updates, and fix form 43

### ISSUE THREAD

**Issue by NeroNightfire** [TheOriginalGeez/Cupid#4]
https://gyazo.com/99587d5d350e54aa681a1ae5a4a2c038

**Comment by TheOriginalGeez** [comment]
SKSE _is_ up to date and form 43s don't need to be fixed. Updating MO2 is kinda low on my priority list but I'll do it for the next time I update.

**Comment by TheOriginalGeez** [comment]
Just realized this was also 22 hours ago. So SKSE is up to date of of now.
