### ISSUE TITLE
Broken download

### ISSUE THREAD

**Issue by Ymir80** [TheOriginalGeez/Cupid#5]
Love the work, man. Well done otherwise. One link is broken. 
skyrim particle patch for enb SSE
![broken](https://user-images.githubusercontent.com/71035454/92636175-9c2c5000-f2df-11ea-9f61-7d46f2f125a1.JPG)

Is it my comp or the wabbajack link?

Thanks for this!

**Comment by galloway** [comment]
It looks like the author of the particle patch made an update on Sep 8th, so either we will have to find the Feb 28th version or wait on an update.

[enbdev forum post with changelog](http://enbseries.enbdev.com/forum/viewtopic.php?t=1499)

**Comment by xSkyrimxPlayerx** [comment]
I'm having the same issue

**Comment by RogueCharlie** [comment]
i cant download the first file that is on the upper comment and /SunJeongs/ Ninirim Collection 3BBB bodyslide v0.2.7z
